# Generated by Django 3.2.16 on 2023-07-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('im_array', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.ManyToManyField(to='inspection_template.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionTemplateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('vehicle_type', models.CharField(choices=[('p', 'Powered Vehicle'), ('t', 'Trailer')], max_length=1)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inspection_template.template')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='questions',
            field=models.ManyToManyField(to='inspection_template.Question'),
        ),
    ]
