# Generated by Django 3.2.16 on 2023-08-07 16:16

from django.db import migrations, models
import inspection_template.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_template', '0002_emails_added_to_template_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontemplateprofile',
            name='emails',
            field=models.TextField(blank=True, help_text='Email addresses separated by commas.\nLink to download inspection report will be sent after inspection.', null=True, validators=[inspection_template.models.validate_email_list]),
        ),
    ]
