# Generated by Django 3.2.16 on 2023-10-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_template', '0004_alter_inspectiontemplateprofile_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='include_tyre_break_section',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
