# Generated by Django 3.2.16 on 2024-01-31 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection_template', '0005_template_include_tyre_break_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontemplateprofile',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspection_template.template'),
        ),
    ]
