# Generated by Django 3.1.2 on 2020-10-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspection_json',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
