# Generated by Django 3.1.2 on 2020-10-31 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0004_auto_20201031_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
