# Generated by Django 3.1.2 on 2020-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_inspectionitem_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='ref',
            field=models.CharField(default='CK56', max_length=64),
            preserve_default=False,
        ),
    ]
