# Generated by Django 3.1.2 on 2020-11-21 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspections', '0010_inspectionitem_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='item_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='ref',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
