# Generated by Django 3.1.2 on 2021-03-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0012_auto_20210210_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['created', '-modified']},
        ),
    ]
