# Generated by Django 3.2.16 on 2023-07-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0013_auto_20210322_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='job_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
